playbooks/ops/profilegen/templates/nodeprofile.j2
playbooks/ops/profilegen/templates/nodeprofileyaml.j2

Modified both  nodeprofile.j2 and nodeprofileyaml.j2 templates to reflect the missing "certificateAuthorities"

Added "certificateAuthorities" in generated Node SDK connection profiles

---

README.md
README.zh.md

prune some duplicated statement
split some long paragraph into structured list
Signed-off-by: david <david-khala@hotmail.com>

Re-organize README.md

---

minifabwin

Exit on Windows if WSL2 is installed

---

docs/README.md

Added some instructions to the docs following recent experiments around using custom chaincode builders.

Instructions for using custom chaincode builders

---

playbooks/ops/templates/ccinstantiate.j2

remove extra whitespace in line  #28, ccinstantiate.j2
Closes issue #65

fix: peer chaincode upgrade space error

---

scripts/mainfuncs.sh

Fixed a spelling mistake in mainfuncs.sh file. The word discover is spelt incorrectly.

Fix discover spelling in mainfuncs.sh

---

README.md
docs/README.md

This PR tightens a bit the language in the README files.
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

Improve READMEs

---

CODEOWNERS
README.md

Update build status

---

docs/README.md
playbooks/common/config_apply.yaml
playbooks/ops/opnames.yaml
playbooks/ops/portainerdown/apply.yaml
playbooks/ops/portainerup/apply.yaml
scripts/mainfuncs.sh

Added portainer web UI

---

playbooks/ops/explorerup/apply.yaml

Use explorer 1.1.3

---

azure-pipelines.yml

Added release 2.3 test

---

envsettings

Change the default fabric release to 2.3.0

---

playbooks/ops/apprun/templates/apprun_go.j2

Signed-off-by: zhenbing <szb@bitm.cn>

Add apprun GOPROXY config

---

ci/fabric-release-test.yml
playbooks/ops/netup/templates/peerenv.j2

Fixed misconfigured couchdb userid and password bug

---

ci/fabric-release-test.yml
minifab

Use ip command when it is available for ip address retrival

---

docs/README.md

update the little problem with docket ( it's sure it's exist ? )

update readme docket -> docker

---

chaincode/simple/java/build.gradle

Fixed java chaincode downlevel dependencies

---

.github/workflows/main.yml

Switch to GitHub Actions for CI

---

docs/README.md
fabops.yaml
playbooks/ops/netup/apply.yaml
spec.yaml

This PR takes  choice1 (single parameter), as discussed in issue #155.
close #155 .

feature: configurable extra option for docker run command

---

docs/ExpandYourNetwork.md

update operation in docs/ExpandYourNetwork.md

---

playbooks/common/config_apply.yaml
playbooks/ops/netup/apply.yaml

Minifab fails when launching the network again #163

Fixed the issue #163

---

.github/workflows/main.yml
DockerfileHub
README.md
docs/README.md
playbooks/ops/update/apply.yaml

Set default branch to main

---

README.md
README.zh.md

close #176 
Signed-off-by: David Liu <david.yx.liu@oracle.com>

Add link to docs in major README

---

DockerfileHub
playbooks/ops/netup/dockerapply.yaml
playbooks/ops/netup/k8sapply.yaml

Upgrade fabric-ca to be fabric-ca:1.5

---

.github/workflows/main.yml

Add support for Fabric 2.4

---

.github/workflows/main.yml
playbooks/ops/imageget/getimage.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2

Remove CI gate for 1.4, Get missed CA images

---

.github/workflows/main.yml
playbooks/ops/imageget/getimage.yaml
playbooks/ops/netup/dockerapply.yaml
playbooks/ops/netup/k8sapply.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2

Roll back Fabric 2.4 support

---

.github/workflows/main.yml

Add build targets for most recent releases
of Fabric

Minimal 2.4 support

---

playbooks/ops/netup/k8stemplates/allnodes.j2

fix fabric-ca TLS handshake error on k8s environment

---

playbooks/ops/certgen/partykeygen.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2

fix fabric-orderer TLS certs for k8s.

---

docs/KnownIssues.md

When the TOC grows in number, it will be very difficult to navigate or search relevant issues, hence I have added a category to make it more structured and organized.
Thanks @litong01 for suggestion the TOC and @ryjones for implementing the TOC.
Signed-off-by: Alex Ramil Aguel <>

Added TOC Category for easier searching/navigation

---

DockerfileHub

followup #225
I noticed that #225 is missing in the latest image in dockerhub.

apply the same patch to DockerfileHub for docker image publishing

---

Dockerfile
DockerfileHub
ansible.cfg
plugins/callback/minifab.py

related #224, I succeeded to bump from 2.9.x to latest 4.x.
I felt that minifab processing goes faster...

bump ansible to latest(4.1.0) from 2.9.x

---

.github/workflows/main.yml

Post docker image to docker hub on push

---

playbooks/ops/netup/dockerapply.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2

x hyperledger/fabric-couchdb:latest (last update: 8 month ago)
o couchdb:latest ( last update: days ago )

bumps couchdb to active version

---

docs/README.md

Fixed link issue and added asset doc

---

playbooks/ops/explorerdown/apply.yaml
playbooks/ops/explorerdown/dockerapply.yaml
playbooks/ops/explorerdown/k8s-clean-service.yaml
playbooks/ops/explorerdown/k8sapply.yaml
playbooks/ops/explorerup/apply.yaml
playbooks/ops/explorerup/dockerapply.yaml
playbooks/ops/explorerup/k8sapply.yaml
playbooks/ops/explorerup/k8stemplates/pods.j2
playbooks/ops/explorerup/k8stemplates/service.j2

Explorer support for Kubernetes

---

playbooks/common/k8s-rm-ingress-entry.yaml
playbooks/ops/portainerdown/apply.yaml
playbooks/ops/portainerdown/dockerapply.yaml
playbooks/ops/portainerdown/k8sapply.yaml
playbooks/ops/portainerup/apply.yaml
playbooks/ops/portainerup/dockerapply.yaml
playbooks/ops/portainerup/k8sapply.yaml
playbooks/ops/portainerup/k8stemplates/pods.j2
playbooks/ops/portainerup/k8stemplates/service.j2

portainer's k8s supporting, based on https://github.com/portainer/k8s/blob/master/deploy/manifests/portainer/

portainer support for kubernetes

---

docs/DeployOntoK8S.md

proxy environment variable is set     x after ingress install    o before ingress install

update docs/DeployOntoK8S.md for reordering instrucction

---

.github/workflows/main.yml

Add support for latest point releases

---

playbooks/ops/certgen/orgkeygen.yaml
playbooks/ops/certgen/templates/v3.j2
spec.yaml

Allow endpoint address to be fqdn

---

README.md

Change chat to discord

---

.github/workflows/main.yml

Signed-off-by: Ryan Humphrey <ryanhumphrey777@gmail.com>
Verifies that each deployed node is actually running.

Github actions: checks status of nodes after deployment
