docs/README.md

This is in relation to **Issue #18**
Basically the original documentation states that for Fabric >= 2.0, approve and commit will do but actual behavior still requires chaincode to be initialized otherwise invoke/query will generate an error:
```
chaincode 'xxx' has not been initialized for this version, must call as init first"
```

Updated README.md with instruction for "Instantiate/Initialize newly installed/upgraded chaincode"

---

minifab
minifabwin

This PR simply changes the main minifab script files to display the spec file being used.
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

Display the spec file being used on starting minifab

---

playbooks/ops/discover/apply.yaml
playbooks/ops/templates/discover.j2

With this change the discover command outputs the path of the files it created, making it easier for the user to find them.
```
Chaincode endorsers file: ./vars/discover/mychannel/simple_endorsers.json
Channel orderers file: ./vars/discover/mychannel/ordererendpoints.json
```
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

Make discover cmd output endorsers and orderers config file paths

---

playbooks/ops/caliperrun/templates/networkconfig.j2

Current caliperrun command will create a report but the SUT section is empty. This fix
will add correct information for that section.

Fixed caliper run report missing SUT section

---

fabops.yaml
playbooks/common/config_apply.yaml
playbooks/ops/certgen/orgkeygen.yaml
playbooks/ops/certgen/templates/crypto-config.j2
playbooks/ops/certgen/templates/v3.j2
playbooks/ops/explorerup/apply.yaml
playbooks/ops/portainerup/apply.yaml
spec.yaml

In addition to the automatic address detection allow the
user to configure the endpoint address in the spec.yaml.
This is useful when the public IP address is not visible to
the server.
Signed-off-by: Eric Vaughn <eric.vaughn@blocledger.com>

Allow endpoint address configuration

---

playbooks/ops/imageget/getimage.yaml
spec.yaml

Fabric release 1.x uses ccenv:latest image which
created issues when underly ccenv:1.4 get updated. This causes
chaincode instantiation errors. This patch will fix the issue.

Fixed chaincode instantiation errors

---

app/callback/app.js
playbooks/ops/caliperrun/apply.yaml
playbooks/ops/caliperrun/templates/benchmarkconfig.j2
playbooks/ops/caliperrun/templates/caliperbind.j2
playbooks/ops/caliperrun/templates/caliperrun.j2
playbooks/ops/caliperrun/templates/networkconfig.j2

Minifabric currently is using caliper 0.3.2 and
fabric sdk 1.4.8, fabric sdk 2.1.0 has came out
with many feature updates, this PR will upgrade
caliper to the latest stable version and take
advantage of the latest features in caliper

Upgrade caliper to 0.4.1

---

docs/README.md
playbooks/ops/ccinstall/apply.yaml

If the user provides a collection configuration file in vars with the
correct name don't overwrite it with the default file.  This
enables the user to set up a custom chaincode with a private
data collection config file that can be used when starting minifab.
Signed-off-by: Eric Vaughn <eric.vaughn@blocledger.com>

Don't overwrite collection config

---

main.sh

Currently chaincode query and invocation parameters
are base64 encoded, when process parametes which contain
spaces, the code can miss characters at the end which
causes issues in some edge cases. This PR fixed the
problem.

Fixed chaincode parameter bug

---

scripts/mainfuncs.sh

docker for windows desktop keeps changing things,
this fix should fix the latest issue with docker
desktop for windows 10 2.5.0.x volumn mounting
issue

Fixed volumn mount issue for windows

---

playbooks/ops/profilegen/templates/nodeprofileyaml.j2

This will change empty peer and orderer lists from `”peer”:` to
`”peer”: []` and  `”orderer”:` to `”orderer”: []` respectively.
Fixes #120
Signed-off-by: Eric Vaughn <eric.vaughn@blocledger.com>

Change empty peer list in yaml connection profile

---

playbooks/ops/netstats/apply.yaml
playbooks/ops/templates/stats.j2

command minifab stats only works when network is
up running. When the network is not running, it
will display an error message which does not work
well in some automated environment. This PR will
fix that issue and display network health percentage
based on how many nodes are running healthy.

Improved stats function

---

app/go/main.go
playbooks/ops/apprun/templates/apprun_go.j2
playbooks/ops/profilegen/templates/goprofile.j2
playbooks/ops/profilegen/templates/goprofileyaml.j2

connection files have been using referenced certs in the past
for golang connection profile, it is not very convinient since
there will be many files to be moved with connection files.
This PR fixed that issue so that all certs will come with
the connection file. Also added example using wallet.

Changed connection file to use embeded certs

---

playbooks/ops/netstats/apply.yaml

minifabric stats command show current fabric network stats, but
it does not show minifabirc itself status like image id and
image creation date and time. This PR will add these extra
information in the stats command

Added minifabric image id and date time in stats command

---

playbooks/common/config_apply.yaml
playbooks/ops/netup/apply.yaml
playbooks/ops/netup/templates/peerenv.j2

This PR is to address a long asked request to expose couchdb
port when couchdb is selected and endpoints to be exposed to
outside of the world. With this PR, one will be able to connect
directly to a couchdb instance when -e true is set.

Expose couchdb port when couchdb is used

---

docs/README.md
fabops.yaml
spec.yaml

CLINAME is also changed when netname is configured in spec.yaml, according to the comment of #143.
fix #143

feature: assign specific NETNAME by spec.yaml

---

playbooks/ops/profilegen/apply.yaml
playbooks/ops/profilegen/templates/javaprofileyaml.j2

This PR supports profilegen for javasdk.
The difference from connection.yaml for nodesdk is:
- add 'client' section
- delete 'channels' section
according to the java app test.
the other sections are the same.

feature: supporting profilegen for javasdk

---

README.md
azure-pipelines.yml

Now the minimum supported fabric version is 1.4.4
this is due to an error only fixed in 2.2.1 for
legacy chaincode.

Remove support to 1.4.1

---

playbooks/ops/netup/apply.yaml

This PR has following feature:
- persists CA data always
- persists couchdb data when minifab -s couchdb called
because current latest master persists data for peers and orderers but not for aboves...

feature: persist data for CA and couchdb

---

docs/README.md

instead of a peer only section,
it is better to show the full result of network bootstrapped by default `spec.yaml`
Close #178
Signed-off-by: David Liu <david.yx.liu@oracle.com>

Illustrate with default full network

---

playbooks/ops/netup/k8stemplates/allnodes.j2

This PR fixes following issue on k8s.
on k8s, environment variables in spec.yaml are reflected in orderer and peer but not in CA.
on the other hand, on docker, all environment variables in spec.yaml are reflected in corresponding container.
with this PR, all environment variables are reflected from spec.yaml in corresponding container on k8s, as the same as docker.

fix reflecting environment variables in fabric-ca container from spec.yaml on k8s

---

playbooks/ops/netup/k8stemplates/allnodes.j2

as the same as docker, let us persist fabric-ca data on k8s.
```
- name: Start all ca nodes
command: >-
docker run -d --network {{ NETNAME }} --name {{ item.fullname }} --hostname {{ item.fullname }}
:
-v {{ item.fullname }}:/etc/hyperledger/fabric-ca-server ## <- persisting CA data
{{ container_options }}
hyperledger/fabric-ca:{{ desiredrelease }}
containers:
- name: {{ nodename }}
image: hyperledger/fabric-ca:1.4
:
volumeMounts:
- { mountPath: "/etc/hyperledger/fabric-ca/idcerts", name: "cert-key-id" }
```

feature: persist fabric-ca data on k8s.

---

README.md
docs/KnownIssues.md

DIscussed with In @litong01 and @aguel in #214 , a file named knownIssues.md is created  to avoid user won't be mistaken as the issues cannot be resolved or due to minifabric problems.
Signed-off-by: Guochao He guochao.he@ibm.com

fix: create knownIssues.md to track known issues

---

Dockerfile

fixes #224
related to #221
```
new versions:
- ansible:              2.9.x
- openshift:            latest(0.12.1)  from 0.11.2
- community.kubernetes: latest(2.0.0)
- kubernets.core:       latest(2.1.1)
- cloud.common:         latest(2.0.3)
```
with above versions, ansible k8s operation is achieved by redirecting as below:
openshift => community.kubernetes => kubernetes.core => cloud.common

bumps dependent lib versions, to involve latest kubernetes.core and cloud.common

---

playbooks/ops/netdown/k8s-clean-allservices.yaml
playbooks/ops/netdown/k8sapply.yaml

cleaning items,  comparing netup operation:
- entries in tcp-services : YES
- entries in service      : YES
- ingress command args    : NO
keep '--tcp-services-configmap=...' in ingress controler command args.
removing command arg causes restarting ingress, it makes down time in other services...
fix #221

remove entries from ingresss k8s in cleanup operation

---

playbooks/ops/netdown/k8s-clean-allservices.yaml

related to #229,
I met a bug in abnormal case, and fixed it.
In normal case , operator does followings before minifab operation.
A) copy kubeconfig to vars/kubeconfig/config
B) install ingress
abnormal case: operator runs minifab without 'B'
in the above case, current playbook/netdown/k8s-clean-allservices.yaml raises an error.
this PR makes 'minifab cleanup' works without error in the above case.

fix a bug in abnormal case on k8s environment.

---

docs/DeployOntoK8S.md
playbooks/common/config_apply.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2
playbooks/ops/netup/k8stemplates/allservices.j2

current minifabric cannot control pod and node binding.
as the result, the peer and it's backend couchdb may be deployed on different worker node,
same situation occurs between peer's CA and peer.
That is not good from point of view of performance or isolation.
This feature involves nodeAffinity with preferredDuringSchedulingIgnoredDuringExecution.
refer https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
in short,
- It makes k8s deploy each pod to the specific node according to node labels.
- k8s deploys a pod in default manner, in following cases:
- if corresponding label is not assigned in any nodes.
- if destination node reached to the max-pods-per-node limitation
three types of label are involved:
* type A (strongest; dock.hlf-fqdn/*) : fully control one pod by …

new feature for k8s, deploying pod(container) to the specific node

---

playbooks/ops/netup/k8stemplates/allnodes.j2

* supporting local-path-provisioner, for persistent storage.
local-path-provisioner seems not support 'subPath' for volumeMounts.

improving on-premise k8s uses.

---

chaincode/simple/java/build.gradle

close #260
tested and worked with following fabric versions
- 1.4.4 (current minimum supported version by minifab)
- 2.0    ( first 2.0 series)
- 2.3.2 ( latest )
so, other version can work with this PR.

fix java chaincode to work with current fabric versions.

---

playbooks/ops/netup/dockerapply.yaml
playbooks/ops/netup/k8stemplates/allnodes.j2

#239 changed couchdb version from fabric-couchdb:latest to couchdb:3
the background of #239:
- fabric-couchdb became deprecated and recent fabric supports couchdb:3 officially.
the reason of revert #239:
- to use couchdb:3, it needs FAB-17993 in peer which legacy fabric doesn't have.
- recent fabric version still supports fabric-couchdb,  so simply revert it.
for supporting variety of versions (legacy to recent), version-image matrix will be needed.

revert #239, couchdb version  v.3 => hyperledger/fabric-couchdb:latest to support legacy fabric-version

---

playbooks/ops/certgen/orgkeygen.yaml
playbooks/ops/certgen/templates/v3.j2

fix cergen for subjectAltName

---

minifab
minifabwin

The previous minifab and minifabwin script only recognized .yaml files, not .yml files, which are the same files with the same extension.
[Issue 382](https://github.com/hyperledger-labs/minifabric/issues/382)

Fix minifab and minifabwin cannot recognize .yml file
